// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","outlineWidth":"4","outlineColor":"rgba(0, 0, 0, 0.5)","width":"160","roundRectRadius":"6"}},
{"name":"DarkPlasma_HideMenuStatusWindow","status":true,"description":"メニュー画面のキャラクターステータスウィンドウを非表示にします","parameters":{}},
{"name":"MNKR_NonGoldWindow","status":true,"description":"メインメニューで所持金ウィンドウを非表示にします。","parameters":{}},
{"name":"Torigoya_CommonMenu","status":true,"description":"メニューからコモンイベント呼び出しプラグイン (v.1.1.0)","parameters":{"base":"","baseItems":"[\"{\\\"name\\\":\\\"タイル切り替え\\\",\\\"commonEvent\\\":\\\"3\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\",\"{\\\"name\\\":\\\"前のマップに戻る\\\",\\\"commonEvent\\\":\\\"2\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\"]"}}
];
