// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","outlineWidth":"4","outlineColor":"rgba(0, 0, 0, 0.5)","width":"160","roundRectRadius":"6"}},
{"name":"MNKR_ReplaceMenu","status":true,"description":"メニューを開く動作を一時的にコモンイベントに置き換えます。","parameters":{"variableCommon":"4"}}
];
