// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MenuSubCommand","status":true,"description":"メニュー画面のサブコマンドプラグイン","parameters":{"サブコマンド":"[\"{\\\"CommandId\\\":\\\"0\\\",\\\"Name\\\":\\\"1\\\",\\\"ParentName\\\":\\\"前マップへ\\\",\\\"HiddenSwitchId\\\":\\\"0\\\",\\\"DisableSwitchId\\\":\\\"0\\\",\\\"Script\\\":\\\"$gameTemp.reserveCommonEvent(2);\\\",\\\"ReturnMap\\\":\\\"true\\\",\\\"MapId\\\":\\\"0\\\",\\\"SelectMember\\\":\\\"false\\\"}\",\"{\\\"CommandId\\\":\\\"0\\\",\\\"Name\\\":\\\"1\\\",\\\"ParentName\\\":\\\"タイル切り替え\\\",\\\"HiddenSwitchId\\\":\\\"0\\\",\\\"DisableSwitchId\\\":\\\"0\\\",\\\"Script\\\":\\\"$gameTemp.reserveCommonEvent(3);\\\",\\\"ReturnMap\\\":\\\"true\\\",\\\"MapId\\\":\\\"0\\\",\\\"SelectMember\\\":\\\"false\\\"}\"]","コマンド追加位置":"0","サブメニュー横幅":"0","選択アクターID変数":"0","ウィンドウスキン":"","オプション消去":"false","ゲーム終了消去":"false","横並びサブメニュー":"false","サブメニュー逐次消去":"true","サブメニューX座標":"0","サブメニューY座標":"0","サブメニュー揃え":"","メニューピクチャ別管理":"false"}},
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","outlineWidth":"4","outlineColor":"rgba(0, 0, 0, 0.5)","width":"160","roundRectRadius":"6"}},
{"name":"DarkPlasma_HideMenuStatusWindow","status":true,"description":"メニュー画面のキャラクターステータスウィンドウを非表示にします","parameters":{}}
];
